[general]
import = [
    "~/.config/alacritty/themes/themes/solarized_dark.toml"
]

[window]
decorations = "Buttonless"
padding = { x = 13, y = 13 }
dynamic_padding = true

[font]
size = 13
offset = { x = 0, y = 3 }
